spring:
  application:
    name: API-GATEWAY

server:
  port: 8882

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

zuul:
  routes:
    USER-CENTER:
      path: /USER-CENTER/**
      serviceId: USER-CENTER
    USER-AUTH:
      path: /USER-AUTH/**
      serviceId: AUTH-SERVICE
  prefix: /V1
