spring:
  application:
    name: api-gateway

server:
  port: 8882

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8881/eureka
  instance:
    prefer-ip-address: true