spring:
  application:
    name: auth-service

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.56.128:3306/spring-cloud-auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8762

security:
  oauth2:
    resource:
      filter-order: 3
#  basic:
#    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
