spring:
  application:
    name: EUREKA-HA

---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    # 服务主机名称
    hostname: peer1
  client:
    # 是否从Eureka Server获取注册信息
    # fetch-registry: false
    # 是否将自己注册到Eureka Server中
    # register-with-eureka: false
    serviceUrl:
      # Eureka服务地址
      defaultZone: http://peer2:8762/eureka/,http://peer3:8763/eureka/
  server:
    # Eureka自我保护模式(开发环境下建议关闭)
    enable-self-preservation: false

---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    # 服务主机名称
    hostname: peer2
  client:
    # 是否从Eureka Server获取注册信息
    # fetch-registry: false
    # 是否将自己注册到Eureka Server中
    # register-with-eureka: false
    serviceUrl:
      # Eureka服务地址
      defaultZone: http://peer1:8761/eureka/,http://peer3:8763/eureka/
  server:
    # Eureka自我保护模式(开发环境下建议关闭)
    enable-self-preservation: false

---
spring:
  profiles: peer3
server:
  port: 8763
eureka:
  instance:
    # 服务主机名称
    hostname: peer3
  client:
    # 是否从Eureka Server获取注册信息
    # fetch-registry: false
    # 是否将自己注册到Eureka Server中
    # register-with-eureka: false
    serviceUrl:
      # Eureka服务地址
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  server:
    # Eureka自我保护模式(开发环境下建议关闭)
    enable-self-preservation: false