spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.56.128:3306/RGP-UC?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
  session:
    store-type: none
  mvc:
    throw-exception-if-no-handler-found: false

security:
  basic:
    enabled: false

roberto:
  growth:
    process:
      security:
        social:
          qq:
            # 对应回调域:www.zzz.cn/login/qq
            appId: 101406228
            appSecret: 762c332bf40517d432db41e17fb169c1
            providerId: qq
          weixin:
            appId: wxd99431bbff8305a0
            appSecret: 60f78681d063590a469f1b297feff3c4
            providerId: weixin
          filterProcessesUrl: /login

logging:
  config: classpath:logback.xml