server:
  port: 8884

spring:
  application:
    name: USER-AUTH

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8881/eureka/


ribbon:
  # 请求处理的超时时间
  ReadTimeout: 120000
  # 请求连接的超时时间
  ConnectTimeout: 30000

logging:
  level:
    roberto.growth.process: debug
