spring:
  application:
    name: CONFIG-SERVICE
  cloud:
    config:
      server:
        git:
          search-paths: RGP-CONFIG
          uri: https://github.com/RobertoHuang/RGP
server:
  port: 8885

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8881/eureka
  instance:
    prefer-ip-address: true
