server:
  port: 8885

spring:
  application:
    name: CONFIG-SERVICE
  cloud:
    config:
      server:
        git:
          search-paths: RGP-CONFIG
          uri: https://github.com/RobertoHuang/RGP
      label: master

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    # Eureka服务注册列表默认是显示主机名+端口
    prefer-ip-address: true